// Ready translated locale messages
export const messages = {
  en: {
    buttons: {
      near: "Search in Nearby Locations",
      metres: "{value} Meters",
      nextnumber: "Next Number",
      getnumber: "Get Number",
      print: "Print",
      ok: "Ok",
      cancel: "Cancel",
      back: "Back",
      save: "Save",
      addButton: "Add",
      register: "Register New Branch",
      changecord: "Change Coordinates",
      submitreview: "Submit Review",
    },
    nav: {
      home: "Home",
      serve: "Serve",
      newbranch: "New Branch",
      display: "Display",
      signin: "Sign In",
      signout: "Sign Out",
      qrpaper: "QR Print",
      qrscan: "QR Scan",
      registration: "Registration Form",
    },
    select: {
      typeofservice: "Type Of Service Provided",
      windownumberselect: "Window Number of Service Provider",
      windownumber: "Window Number ",
    },
    alerts: {
      currentnumber: "Current Number {value}",
      distance: "The user distance is { value } meters",
      servicerating: "Service Reviews",
      totalnumbers: "All the numbers in line",
      currentlyserved: "Numbers that are being served",
    },
    text: {
      fullname: "Type Your Full Name",
      usecamera: "Scan QR Code with your camera to get in line",
      service: "Service",
      forgotpassword: "Forgot Password",
      email_sign_in: "Type Email to Sign in",
      email_branch: "Branch Email Address",
      password: "Type Password ",
      passwordmin: "Password must contain at least {value} characters",
      passwordchange: "Change Password",
      oldpassword: "Your Old Password",
      confirmpassword: "Confirm Password",
      branch_name: "Branch name of service provider",
      profile: "Branch Profile",
      servicewindow: "Each type of service has a que",
      timenotset: "Time Not Set",
      maplocation: "Location on Map",
      howexperince: "How was your experince with {value}",
    },
    labels: {
      name: "Name: ",
      email: "Email Address:",
      password: "Password:",
      curpassword: "Current Password",
      newpassword: "New Password",
      branch: "Branch Name:",
      phone: "Phone Number:",
      servicetype: "Type of activity:",
      servicewindow: "Types of Services:",
      opentime: "Open Time:",
      closetime: "Closing Time:",
      logo: "Logo: ",
      window: "Window:",
      number: "Number:",
      review: "Rating:",
      comment: "Comment:",
    },
  },

  // ANOTHER LANGUAGE

  "ar-ly": {
    buttons: {
      near: "االبحث في نطاق قريب",
      metres: "{value} متر",
      nextnumber: "الرقم التالي",
      getnumber: "طلب رقم",
      print: "طباعة",
      ok: "موافق",
      cancel: "الغاء الأمر",
      back: "الرجوع",
      save: "تخزين",
      addButton: "إضافة",
      register: "تسجيل فرع جديد",
      changecord: "تغيير الاحداثيات",
      submitreview: "ارسال التقييم",
    },
    nav: {
      home: "الرئيسية",
      serve: "خدمة",
      newbranch: "فرع جديد",
      display: "شاشة الآرقام",
      signin: "تسجيل الدخول",
      signout: "تسجيل الخروج",
      qrpaper: "QR طباعة",
      qrscan: "QR كاميرا",
      registration: "نموذج التسجيل",
    },
    select: {
      typeofservice: "نوع الخدمة المقدمة",
      windownumberselect: "رقم شباك مقدم الخدمة",
      windownumber: " شباك رقم ",
    },
    alerts: {
      currentnumber: "الرقم الحالي {value}",
      distance: "يبعد المستخدم مسافة { value } متر",
      servicerating: "تقييم الخدمات",
      totalnumbers: "الارقام الكلية في الطابور",
      currentlyserved: "الارقام التي يتم خدمتها",
    },
    text: {
      fullname: "اسمك الثلاتي",
      usecamera: "صور الرمز بالكاميرا لطلب طابور",
      service: "خدمة",
      forgotpassword: "نسيت كلمة المرور",
      email_sign_in: "البريد الإلكتروني لتسجيل الدخول",
      email_branch: "البريد الإلكتروني للفرع",
      password: "كلمة المرور",
      passwordmin: "كلمة مرور تتكون من اكثر من {value} حروف او ارقام",
      oldpassword: "كلمة المرور القديمة",
      confirmpassword: "تأكيد كلمة المرور",
      passwordchange: "تغيير كلمة المرور",
      branch_name: "اسم فرع موزع الخدمة او الشركة",
      profile: "ملف تعريف الفرع",
      servicewindow: "   كل نوع خدمة له طابور خاص",
      timenotset: "لم يتم تحديد الوقت",
      maplocation: "الموقع في الخريطة",
      howexperince: "كيف كانت تجربتك في {value}",
    },
    labels: {
      name: "الإسم:",
      email: "البريد الإلكتروني:",
      password: "كلمة المرور:",
      curpassword: "كلمة المرور الحالية:",
      newpassword: "كلمة المرور الجديدة:",
      branch: "اسم الفرع:",
      phone: "رقم الهاتف:",
      servicetype: "نوع النشاط:",
      servicewindow: "انواع الخدمات:",
      opentime: "بداية ساعات العمل:",
      closetime: "نهاية ساعات العمل:",
      logo: "الشعار:",
      window: "شباك:",
      number: "رقم:",
      review: "التقييم: ",
      comment: "التعليق",
    },
  },
};
